name: Binary releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Tag manifest images
        run: |
          mkdir -p ./releases/manifests
          TAG=${GITHUB_REF#refs/*/}
          cat ./config/namespace/ > /releases/manifests/triggermesh-core.yaml
          find config/2*.yaml -exec cat {} \; -exec echo \; -exec echo --- \; -exec echo \; >> /releases/manifests/triggermesh-core.yaml
          find config/3*.yaml -exec cat {} \; -exec echo \; -exec echo --- \; -exec echo \; >> /releases/manifests/triggermesh-core-crds.yaml
          cat ./config/configmaps/*.yaml >> /releases/manifests/triggermesh-core.yaml
          sed -i 's/:dev/:$TAG/g' ./config/manifests/5*.yaml >> /releases/manifests/triggermesh-core.yaml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
